// SPT-Fika configurator — form state → docker-compose.yml + .env + README bundle.
// No backend, no framework: the form mirrors docs/env-vars.md (the image contract),
// emits compose/.env client-side, and downloads a zip (see zip.js).

// ---- schema: the form surface. Defaults = the most common Fika server. ----
const TABS = [
  { id: "general", label: "GENERAL", fields: [
    { key: "serverName", label: "Server name", type: "text", def: "spt-fika",
      help: "Container name + compose service id.", re: /^[a-zA-Z0-9_.-]+$/ },
    { key: "dataDir", label: "Data directory", type: "text", def: "./server-data",
      help: "Host path bind-mounted to /opt/server (profiles, mods, configs persist here)." },
    { key: "gamePort", label: "Game port", type: "number", def: 6969,
      help: "Host port mapped to the server's 6969. Clients connect here.", min: 1, max: 65535 },
    { key: "arch", label: "Host architecture", type: "radio", def: "x86_64",
      options: [["x86_64", "x86_64 (Intel/AMD)"], ["aarch64", "aarch64 (ARM)"]],
      help: "Headless is x86-only — selecting ARM disables the HEADLESS tab." },
    { key: "listenAll", label: "Listen on all networks", type: "toggle", def: true,
      help: "Bind 0.0.0.0 so LAN / remote Fika clients can reach the server. Usually on." },
  ]},
  { id: "version", label: "VERSION", fields: [
    { key: "sptMajor", label: "SPT major", type: "select", def: "4",
      options: [["4", "4.0 (current)"], ["3", "3.11 (LTS — build unverified)"]],
      help: "Picks the server build/run path." },
    { key: "sptVersion", label: "SPT version", type: "text", def: "4.0.13",
      help: "Auto-filled to the latest stable 4.0.x from the Forge on load; edit to pin a version. (A valid sp-tarkov/server-csharp tag.)", req: true },
    { key: "installFika", label: "Install Fika", type: "toggle", def: true,
      help: "Install the Fika server mod on first boot." },
    { key: "fikaVersion", label: "Fika version", type: "text", def: "2.3.2",
      help: "Auto-filled to the latest Fika server release on load; edit to pin a version. (Tag of project-fika/Fika-Server-CSharp.)", req: true },
  ]},
  { id: "headless", label: "HEADLESS", arch: "x86_64", fields: [
    { key: "headlessEnabled", label: "Enable headless client", type: "toggle", def: false,
      help: "Adds a headless Fika client (zhliau image) that hosts raids unmanned. x86-only." },
    { key: "numHeadlessProfiles", label: "Headless profiles", type: "number", def: "",
      help: "How many headless profiles the server creates on boot (sets headless.profiles.amount in fika.jsonc). Usually 1.", min: 0, max: 10 },
    { key: "headlessProfileId", label: "Headless profile ID", type: "text", def: "",
      help: "The server generates this on first boot — grab it from the logs, then set HEADLESS_PROFILE_ID in .env. Leave blank for now." },
    { key: "headlessTag", label: "Headless image tag", type: "text", def: "latest",
      help: "Tag of ghcr.io/zhliau/fika-headless-docker." },
  ]},
  { id: "mods", label: "MODS", fields: [
    { key: "useModsync", label: "Install ModSync", type: "toggle", def: false,
      help: "Adds the Corter-ModSync server mod so clients keep their mods in sync with the server. SPT 4.0 only for now (3.11 needs Corter's original mod)." },
    { key: "modsyncVersion", label: "ModSync version", type: "text", def: "0.12.5",
      help: "Release tag of Dildz/ModSync-for-SPT4.0." },
    { key: "modUrls", label: "Mod URLs", type: "textarea", def: "",
      help: "One archive URL per line (.zip / .7z). Each must contain user/ and/or BepInEx/ at its root." },
  ]},
  { id: "ops", label: "OPS", fields: [
    { key: "restartPolicy", label: "Restart policy", type: "select", def: "unless-stopped",
      options: [["unless-stopped", "unless-stopped"], ["always", "always"],
                ["on-failure", "on-failure"], ["no", "no"]],
      help: "Docker restart policy for the service." },
    { key: "autoUpdateFika", label: "Auto-update Fika", type: "toggle", def: false,
      help: "Reinstall the pinned Fika version on boot if already installed (preserves fika.jsonc)." },
    { key: "verboseLogs", label: "Verbose logs", type: "toggle", def: true,
      help: "Off filters high-frequency request spam (keepalive / ping / heartbeat)." },
    { key: "healthcheck", label: "Server healthcheck", type: "toggle", def: true,
      help: "Adds a healthcheck on the server. Headless + web app wait for it before starting (run with `docker compose up -d --wait`). Off = they start as soon as the server container does." },
    { key: "webapp", label: "Fika Web App", type: "toggle", def: false,
      help: "Adds the Fika Web App container (lacyway/fikawebapp) — a browser admin UI: accounts, item sending, profiles, headless control. Needs Fika." },
    { key: "webappApiKey", label: "Web App API key", type: "text", def: "",
      help: "Generated by the Fika server (you'll have it after the first boot). Leave blank now and fill WEBAPP_API_KEY in .env later, or paste it here." },
    { key: "webappPort", label: "Web App port", type: "number", def: 8080, min: 1, max: 65535,
      help: "Host port for the web app UI over http. Put it behind your reverse proxy for HTTPS." },
  ]},
  { id: "adv", label: "ADV", fields: [
    { key: "puid", label: "PUID", type: "number", def: 1000, min: 0, max: 65535,
      help: "User id the server runs as / owns the mount." },
    { key: "pgid", label: "PGID", type: "number", def: 1000, min: 0, max: 65535,
      help: "Group id the server runs as." },
    { key: "userName", label: "User name", type: "text", def: "spt", re: /^[a-zA-Z0-9_-]+$/,
      help: "Name for a created user (ignored if PUID already exists on the host)." },
    { key: "groupName", label: "Group name", type: "text", def: "spt", re: /^[a-zA-Z0-9_-]+$/,
      help: "Name for a created group." },
  ]},
];

const FIELDS = {};
for (const t of TABS) for (const f of t.fields) FIELDS[f.key] = f;

const STORE_KEY = "spt-fika-configurator";
let state = loadState();
let activeTab = "general";
let previewMode = "compose"; // "compose" | "env"

function loadState() {
  const s = {};
  for (const k in FIELDS) s[k] = FIELDS[k].def;
  try { Object.assign(s, JSON.parse(localStorage.getItem(STORE_KEY) || "{}")); } catch {}
  return s;
}
function saveState() { try { localStorage.setItem(STORE_KEY, JSON.stringify(state)); } catch {} }

// ---- validation: returns { key: message } for invalid fields ----
function validate() {
  const e = {};
  for (const k in FIELDS) {
    const f = FIELDS[k], v = state[k];
    if (f.type === "number" && v !== "") {
      const n = Number(v);
      if (!Number.isInteger(n) || n < f.min || n > f.max) e[k] = `Must be ${f.min}–${f.max}.`;
    }
    if (f.req && String(v).trim() === "") e[k] = "Required.";
    if (f.re && String(v).trim() !== "" && !f.re.test(String(v))) e[k] = "Invalid characters.";
  }
  return e;
}

// ---- emitters ----
function headlessOn() { return state.headlessEnabled && state.arch === "x86_64"; }

function emitCompose() {
  const s = state, svc = s.serverName || "spt-fika", net = `${svc}-net`;
  const L = [
    "# SPT-FIKA Server — docker-compose.yml",
    "# Generated by the SPT-Fika configurator",
    "# https://github.com/Dildz/SPT-Fika-Docker-Guide",
    "",
    `name: ${svc}`,
    "",
    "services:",
    `  ${svc}:`,
    "    image: ghcr.io/dildz/spt-fika-server:${SPT_VERSION}",
    `    container_name: ${svc}`,
    `    restart: ${s.restartPolicy}`,
    "    ports:",
    `      - "${s.gamePort}:6969"`,
    "    env_file: .env",
    "    volumes:",
    `      - ${s.dataDir}:/opt/server`,
  ];
  if (s.healthcheck) {
    const ep = s.installFika ? "/fika/presence/get" : "/launcher/ping";
    L.push(
      "    healthcheck:",
      `      test: ["CMD-SHELL", "curl -sfk https://localhost:6969${ep}"]`,
      "      interval: 10s",
      "      timeout: 5s",
      "      retries: 30",
      "      start_period: 30s",
    );
  }
  L.push("    networks:", `      - ${net}`);
  if (headlessOn()) {
    L.push(
      "",
      "  # Headless Fika client — hosts raids unmanned (interim zhliau image).",
      "  # PROFILE_ID is generated by the server on first boot; set HEADLESS_PROFILE_ID in .env then.",
      `  ${svc}-headless:`,
      "    image: ghcr.io/zhliau/fika-headless-docker:${HEADLESS_TAG:-latest}",
      `    container_name: ${svc}-headless`,
      `    restart: ${s.restartPolicy}`,
      "    depends_on:",
      `      ${svc}:`,
      `        condition: ${s.healthcheck ? "service_healthy" : "service_started"}`,
      "    ports:",
      '      - "25565:25565/udp"',
      "    environment:",
      `      SERVER_URL: ${svc}`,
      '      SERVER_PORT: "6969"',
      '      PROFILE_ID: "${HEADLESS_PROFILE_ID}"',
      `      UID: "${s.puid}"`,
      `      GID: "${s.pgid}"`,
      `      USE_MODSYNC: "${s.useModsync && s.sptMajor === "4" ? "true" : "false"}"`,
      '      AUTO_RESTART_ON_RAID_END: "false"',
      '      SAVE_LOG_ON_EXIT: "true"',
      // ponytail: wine sync left at the image default — esync was an experimental flag; the target
      // is ntsync (as Outshynd's headless uses), to be settled when the native headless image lands.
      "    volumes:",
      "      # Put your SPT + EFT headless CLIENT files here — the headless runs a real game client.",
      "      - ./headless-data:/opt/tarkov",
      "    networks:",
      `      - ${net}`,
    );
  }
  if (s.webapp) {
    L.push(
      "",
      "  # Fika Web App — server admin UI. Generate the API key on the server, then set WEBAPP_API_KEY in .env.",
      "  # Default login: admin / Admin123!  (change it immediately). Put it behind a reverse proxy for HTTPS.",
      `  ${svc}-webapp:`,
      "    image: lacyway/fikawebapp:latest",
      `    container_name: ${svc}-webapp`,
      `    restart: ${s.restartPolicy}`,
      "    depends_on:",
      `      ${svc}:`,
      `        condition: ${s.healthcheck ? "service_healthy" : "service_started"}`,
      "    environment:",
      '      PORT: "5000"',
      '      API_KEY: "${WEBAPP_API_KEY}"',
      `      BASE_URL: "https://${svc}:6969"`,
      "    ports:",
      `      - "${s.webappPort}:5000"`,
      "    command:",
      '      - "--quiet-logs"',
      "    volumes:",
      "      - webappdata:/app/data",   // named volume → no root-owned host folder to get stuck on
      "    networks:",
      `      - ${net}`,
    );
  }

  // One bridge network for the stack — services resolve each other by name on it.
  L.push("", "networks:", `  ${net}:`, `    name: ${net}`, "    driver: bridge");

  // Named volume for the web app data (avoids the bind-mount perms trap).
  if (s.webapp) L.push("", "volumes:", "  webappdata:");

  return L.join("\n") + "\n";
}

function emitEnv() {
  const s = state;
  const L = [
    "# SPT-FIKA Server — environment (.env)",
    "# Generated by the SPT-Fika configurator. See docs/env-vars.md.",
    "",
    `SPT_MAJOR=${s.sptMajor}`,
    `SPT_VERSION=${s.sptVersion}`,
    `INSTALL_FIKA=${s.installFika}`,
    `FIKA_VERSION=${s.fikaVersion}`,
    `AUTO_UPDATE_FIKA=${s.autoUpdateFika}`,
    `LISTEN_ALL_NETWORKS=${s.listenAll}`,
    `VERBOSE_LOGS=${s.verboseLogs}`,
    `PUID=${s.puid}`,
    `PGID=${s.pgid}`,
    `USER_NAME=${s.userName}`,
    `GROUP_NAME=${s.groupName}`,
  ];
  if (headlessOn()) {
    L.push(`HEADLESS_TAG=${s.headlessTag}`);
    L.push(`HEADLESS_PROFILE_ID=${s.headlessProfileId}`);
    if (String(s.numHeadlessProfiles).trim() !== "") L.push(`NUM_HEADLESS_PROFILES=${s.numHeadlessProfiles}`);
  }
  if (s.useModsync && s.sptMajor === "4") {
    L.push("USE_MODSYNC=true");
    L.push(`MODSYNC_VERSION=${s.modsyncVersion}`);
  }
  if (s.webapp) L.push(`WEBAPP_API_KEY=${s.webappApiKey}`);
  const urls = String(s.modUrls).trim().split(/\s+/).filter(Boolean);
  if (urls.length) L.push(`MOD_URLS="${urls.join(" ")}"`);
  return L.join("\n") + "\n";
}

function emitReadme() {
  const s = state;
  return [
    "# SPT-FIKA Server — quick start",
    "",
    "Generated by the SPT-Fika configurator.",
    "",
    "1. Install Docker + Docker Compose.",
    "2. Put `docker-compose.yml` and `.env` in a folder together.",
    "3. Start it:",
    "",
    "   ```",
    "   docker compose up -d",
    "   ```",
    "",
    `4. Watch the first boot (Fika install + server start):`,
    "",
    "   ```",
    `   docker compose logs -f ${s.serverName}`,
    "   ```",
    "",
    `5. Connect the SPT launcher to \`https://<your-server-ip>:${s.gamePort}\`.`,
    "",
    `Server files persist in \`${s.dataDir}\`. To change settings, regenerate the bundle and \`docker compose up -d\` again.`,
    "",
  ].join("\n");
}

function bundleFiles() {
  return [
    { name: "docker-compose.yml", content: emitCompose() },
    { name: ".env", content: emitEnv() },
    { name: "README.md", content: emitReadme() },
  ];
}

// ---- rendering ----
const $ = (id) => document.getElementById(id);

function renderTabs() {
  const bar = $("tabbar");
  bar.innerHTML = "";
  for (const t of TABS) {
    const b = document.createElement("button");
    b.className = "tab" + (t.id === activeTab ? " active" : "");
    b.textContent = t.label;
    const disabled = t.arch && t.arch !== state.arch;
    if (disabled) { b.classList.add("disabled"); b.title = "x86_64 only"; }
    b.onclick = () => { if (!disabled) { activeTab = t.id; render(); } };
    bar.appendChild(b);
  }
}

function renderFields() {
  const tab = TABS.find((t) => t.id === activeTab);
  const host = $("fields");
  host.innerHTML = "";
  const errs = validate();
  const tabDisabled = tab.arch && tab.arch !== state.arch;

  for (const f of tab.fields) {
    const wrap = document.createElement("label");
    wrap.className = "field";

    const head = document.createElement("div");
    head.className = "field-label";
    head.textContent = f.label;
    wrap.appendChild(head);

    let input;
    const modsyncField = f.key === "useModsync" || f.key === "modsyncVersion";
    const disabled = tabDisabled
      || (tab.id === "headless" && f.key !== "headlessEnabled" && !state.headlessEnabled)
      || (f.key === "modsyncVersion" && !state.useModsync)
      || (modsyncField && state.sptMajor !== "4") // ModSync auto-install is SPT 4 only
      || ((f.key === "webappApiKey" || f.key === "webappPort") && !state.webapp);

    if (f.type === "toggle") {
      input = document.createElement("input");
      input.type = "checkbox";
      input.checked = !!state[f.key];
      input.onchange = () => set(f.key, input.checked, true);
      wrap.classList.add("toggle");
    } else if (f.type === "select") {
      input = document.createElement("select");
      for (const [val, lbl] of f.options) {
        const o = document.createElement("option");
        o.value = val; o.textContent = lbl; o.selected = state[f.key] === val;
        input.appendChild(o);
      }
      input.onchange = () => set(f.key, input.value, true);
    } else if (f.type === "radio") {
      input = document.createElement("div");
      input.className = "radio-row";
      for (const [val, lbl] of f.options) {
        const r = document.createElement("button");
        r.type = "button";
        r.className = "radio" + (state[f.key] === val ? " active" : "");
        r.textContent = lbl;
        r.onclick = () => set(f.key, val, true);
        input.appendChild(r);
      }
    } else if (f.type === "textarea") {
      input = document.createElement("textarea");
      input.rows = 5;
      input.value = state[f.key];
      input.oninput = () => set(f.key, input.value, false);
    } else {
      input = document.createElement("input");
      input.type = f.type === "number" ? "number" : "text";
      input.value = state[f.key];
      input.oninput = () => set(f.key, input.value, false);
    }
    if (disabled && input.tagName) input.disabled = true;
    wrap.appendChild(input);

    const help = document.createElement("div");
    help.className = "help";
    help.textContent = f.help;
    wrap.appendChild(help);

    if (errs[f.key]) {
      const err = document.createElement("div");
      err.className = "error";
      err.textContent = errs[f.key];
      wrap.appendChild(err);
    }
    host.appendChild(wrap);
  }
}

function renderPreview() {
  $("preview-name").textContent = previewMode === "compose" ? "docker-compose.yml" : ".env";
  $("btn-yaml").classList.toggle("active", previewMode === "compose");
  $("btn-env").classList.toggle("active", previewMode === "env");
  const text = previewMode === "compose" ? emitCompose() : emitEnv();
  const code = $("code");
  code.innerHTML = "";
  text.replace(/\n$/, "").split("\n").forEach((line, i) => {
    const ln = document.createElement("span");
    ln.className = "ln";
    ln.textContent = String(i + 1).padStart(3, " ");
    const tx = document.createElement("span");
    tx.textContent = " " + line;
    const row = document.createElement("div");
    row.append(ln, tx);
    code.appendChild(row);
  });

  const errs = validate();
  $("download").disabled = Object.keys(errs).length > 0;
}

function render() { renderTabs(); renderFields(); renderPreview(); }

// rerenderTab=true when a change can flip disabled/active states (toggle/select/radio);
// for free-typing we only refresh the preview so the input keeps focus.
function set(key, val, rerenderTab) {
  const f = FIELDS[key];
  state[key] = f && f.type === "number" && val !== "" ? Number(val) : val;
  if (key === "sptVersion") state.__pinnedSpt = true;   // user edited → stop auto-filling
  if (key === "fikaVersion") state.__pinnedFika = true;
  saveState();
  if (rerenderTab) render();
  else { renderFields(); renderPreview(); }
}

// ---- actions ----
function init() {
  render();
  // Clamp the preview box to the form box height — scroll the YAML inside, so the
  // two columns always line up regardless of which tab (and how many fields) is shown.
  const formPanel = document.querySelector(".form-panel");
  const previewPanel = document.querySelector(".preview-panel");
  if (formPanel && previewPanel && "ResizeObserver" in window) {
    const syncPreviewHeight = () => { previewPanel.style.height = formPanel.offsetHeight + "px"; };
    new ResizeObserver(syncPreviewHeight).observe(formPanel);
    syncPreviewHeight();
  }
  $("btn-yaml").onclick = () => { previewMode = "compose"; renderPreview(); };
  $("btn-env").onclick = () => { previewMode = "env"; renderPreview(); };
  $("copy").onclick = async () => {
    const text = previewMode === "compose" ? emitCompose() : emitEnv();
    try { await navigator.clipboard.writeText(text); flash($("copy"), "Copied"); } catch {}
  };
  $("download").onclick = () => {
    const bytes = makeZip(bundleFiles());
    const blob = new Blob([bytes], { type: "application/zip" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${state.serverName}-bundle.zip`; a.click();
    URL.revokeObjectURL(url);
  };
  $("reset").onclick = () => {
    for (const k in FIELDS) state[k] = FIELDS[k].def;
    delete state.__pinnedSpt; delete state.__pinnedFika;
    saveState(); render(); detectVersions();
  };
  bootReadout();
  initNav();
  detectVersions();
}

// Live version defaults — fetch the latest on load, fall back to the static field
// defaults if a source is unreachable/rate-limited. SPT from the Forge (clean 4.0.x,
// no beta tags); the Fika *server* version from its GitHub releases — what
// install_fika.sh actually downloads. (The Forge "Project Fika" entry tracks the
// client plugin, which can run ahead of the server.) A field the user has edited
// is pinned and never overwritten.
function detectVersions() {
  if (typeof fetch !== "function") return;
  const getJson = (url) =>
    fetch(url, { headers: { Accept: "application/json" } }).then((r) => (r.ok ? r.json() : Promise.reject(r.status)));

  getJson("https://forge.sp-tarkov.com/api/v0/spt/versions?filter%5Bspt_version%5D=%5E4.0.0&sort=-version&per_page=1&fields=version")
    .then((j) => { const v = j && j.data && j.data[0] && j.data[0].version; if (v && !state.__pinnedSpt) applyVersion("sptVersion", v); })
    .catch(() => {});

  getJson("https://api.github.com/repos/project-fika/Fika-Server-CSharp/releases/latest")
    .then((j) => { const v = j && j.tag_name && j.tag_name.replace(/^v/, ""); if (v && !state.__pinnedFika) applyVersion("fikaVersion", v); })
    .catch(() => {});
}
function applyVersion(key, v) {
  if (state[key] === v) return;
  state[key] = v; saveState(); renderFields(); renderPreview();
}

// Scroll-spy: highlight the top-bar link for whichever section is in view.
function initNav() {
  const links = [...document.querySelectorAll(".nav a[data-nav]")];
  if (!links.length || !("IntersectionObserver" in window)) return;
  const byId = new Map(links.map((a) => [a.getAttribute("href").slice(1), a]));
  const io = new IntersectionObserver((entries) => {
    for (const e of entries) {
      if (!e.isIntersecting) continue;
      links.forEach((l) => l.classList.remove("active"));
      const a = byId.get(e.target.id);
      if (a) a.classList.add("active");
    }
  }, { rootMargin: "-45% 0px -50% 0px" });
  byId.forEach((_, id) => { const el = $(id); if (el) io.observe(el); });
}

// Signature hero animation: reveal a faux assemble manifest line by line.
function bootReadout() {
  const el = $("boot");
  if (!el) return;
  const lines = [
    '<span class="cmd">spt-fika@deploy:~$</span> ./assemble.sh --fika',
    '<span class="ok">✓</span> image    <span class="key">ghcr.io/dildz/spt-fika-server:4.0.13</span>',
    '<span class="ok">✓</span> fika mod <span class="key">2.3.2</span>',
    '<span class="ok">✓</span> listen   <span class="key">0.0.0.0:6969</span>',
    '<span class="ok">✓</span> mods     <span class="key">0 extra</span>',
    '<span class="ok">✓</span> bundle   compose · .env · readme',
    '<span class="ready">● READY</span> — extract &amp; docker compose up -d',
  ];
  if (matchMedia("(prefers-reduced-motion: reduce)").matches) {
    el.innerHTML = lines.join("\n"); return;
  }
  let i = 0;
  (function next() {
    if (i >= lines.length) return;
    el.innerHTML += (i ? "\n" : "") + lines[i++];
    setTimeout(next, 360);
  })();
}

function flash(btn, msg) {
  const old = btn.textContent;
  btn.textContent = msg;
  setTimeout(() => { btn.textContent = old; }, 1200);
}

document.addEventListener("DOMContentLoaded", init);
